# -*- coding: utf-8 -*-
"""lab3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18jDKQMzgGQHceac5I-Jlp2ZZ6vJP6QvR
"""

#lab 1
r=int(input("enter the number of raisins"))
ar=int(input("enter the number of apricots"))
a=int(input("enter the number of almonds"))
t=r+ar+a
print("the percentage of raisins productions is :",r/t*100)
print("the percentage of apricots productions is :",ar/t*100)
print("the percentage of almonds productions is :",a/t*100)

#lab 2
a=30
b=25
c=35
d=45
e=20
f=25
g=b/a*100
h=c/d*100
i=e/f*100
print("the diabetes detection accuracy is ",g)
print("the heart disease detection accuracy is ",h)
print("the cancer detection accuracy is ",i)
print("the overall accuracy of the disease detector is ",(g+h+i)/3)

#lab 3
x=int(input("enter the value of x:"))
a=(x**2)+(3*x-4)
if x==2:
  print("the values of the quadratic equation when x = ", x , " is ",a)
elif x==1:
  print("the values of the quadratic equation when x = ", x , " is ",a)
elif x==-1:
  print("the values of the quadratic equation when x = ", x , " is ",a)

#lab 4
i=1
countodd=0
counteven=0
while i<=100:
  if i%2==0:
    counteven=counteven+i
  else:
    countodd=countodd+i
  i+=1
print("the sum of all odd and even numbers 1 nad 100 is",counteven)
print("the sum of all odd and even numbers 1 nad 100 is",countodd)
print()

#lab 5
a=int(input("enter a number"))
fact=1
i=1
while i<=a:
  fact=fact*i
  i+=1
print("the factorial of the given number is",fact)

#lab 6
for i in range(1,5):
  for j in range(1,11):
    print(i,"x",j,"=",i*j,end="\t")
  print()

#lab 7
a=int(input("enter the first number"))
b=int(input("enter the second number"))
c=input("enter the operation you want to perform")

if c=='+':
  print(a+b)
elif c=='-':
 print(a-b)
elif c=='*':
 print(a*b)
elif c=='/':
 if b==0:
  print("0 cannot be divided")
 else:
  print(a/b)
else:
  print("invalid credentials")

#lab 8
#to print fibanacci series less than 100
a=0
b=1
print('0')
print('1')
c=a+b
while c<100:
  print(c)
  a=b
  b=c
  c=a+b

#to print certain number of fibonacci series
a=0
b=1
i=3
while i<=15:
  c=a+b
  a=b
  b=c
  i+=1
  print(c)

#to print fibonacci series between certain ranges
x=int(input("enter starting number"))
y=int(input("enter ending number"))
a=0
b=1
while a<y:
  if a>=x:
    print(a)
  c=a+b
  a=b
  b=c

#lab 10
a=int(input("enter the starting range"))
b=int(input("enter the ending range"))
c=int(input("enter the number you want to count"))
count=0
for i in range(a,b+1):
  d=i
  while d!=0:
    if d%10==c:
     count+=1
    d=d//10
print(count)

#to count the no of vowels
a=input("enter a string")
count=0
for i in a:
  if i in "aeiouAEIOU":
    count=count+1
print("the numbers of vowels present inthe given string is",count)

#lab 11
a=int(input("enter the weight of the package : "))
b=input("enter the destination : ")
if b=="domestic" or b=="DOMESTIC":
   if a<=1:
    print("cost is 50")
   else:
    print("cost is",50+(a-1)*10)
else:
 if a<=1:
  print("cost is 100")
 else:
  print("cost is ",500 +(a-1)*100)

#lab 12
a=int(input("enter the car price : "))
discount=0
if a<1000000:
  print("there is no discount")
elif a>=1000000 and a<=2000000:
  b=discount=0.05
  print("the percentage of discount granted is :",b)
  print(discount*a)
elif a>=2000000 and a<=3000000:
  c=discount=0.075
  print("the percentage of discount granted is :",c)
  print(discount*a)
elif a>3000000:
  d=discount=0.10
  print("the percentage of discount granted is :",d)
  print(discount*a)
d=a-(discount*a)
print("the price of the car is ", d)

#lab 13
a=int(input("enter the number to check"))
d=0
b=a
while a!=0:
  c=a%10
  d=(c*c*c)+d
  a=a//10
if d==b:
  print("the given number is an armstrong number")
else:
  print("the given number is not an armstrong number")

#to print armstrong numbers between a range
for a in range(1,200):
 d=0
 b=a
 while a!=0:
  c=a%10
  d=(c*c*c)+d
  a=a//10
 if d==b:
  print(d)

# to print n number of armstrong numbers
n=int(input("enter the number of elements"))
count=0
a=1
while count<n:
  b=a
  d=0
  while b!=0:
    c=b%10
    d=(c*c*c) + d
    b=b//10
  if d==a:
    print(a)
    count+=1
  a+=1

#lab 14
a=int(input("enter the starting range"))
b=int(input("enter the ending range"))
for j in range(a,b):
  if j > 1:
    for i in range(2,j):
      if j%i==0:
       print(j)
       break

#to check if a given number is prime or composite
a=int(input("enter the number to check"))
b=2
if a>1:
 for i in range(b,a):
  if a%i==0:
    print("composite")
    break
  else:
    print("prime")
    break

#to print prime numbers till n
a=int(input("enter the upper limit"))
for i in range(2,a):
  for j in range(2,i):
    if i%j==0:
     print(i)
     break

#lab 15
a=int(input("enter a number"))
b=a
r=0
while a!=0:
  d=a%10
  r=r*10+d
  a=a//10
if r==b:
  print("the given number is palindrome")
else:
  print("the given number is not palindrome")

#lab 16.a
a=input("enter a string")
b=a[::-1]
if b==a:
 print("the given string is palindrome")
else:
  print("the given string is not palindrome")

#lab 16.b
c=input("enter a string")
d=c[::-1]
print(d)

#16.c
x=input("enter the string")
y=input("enter the character to remove")
r=x.replace(y,'')
print(r)

p=input("enter the string")
q=int(input("enter the index of character to remove"))
s=p[:q] + p [q+1:]
print(s)

#16.d
u="hyy"
count1=0
for v in u:
  count1=count1+1
print(count1)
print(len(u))

#16.e
ab="hello world"
count=0
for i in ab:
  if i!=" ":
   count=count+1
print(count)

#lab 17.a
a=input("enter a string : ")
b=a.split()
for i in b:
  if len(i)%2==0:
    print(i)

#17.b
c=input("enter a string : ")
d=len(c)//2
e=c[0:d]
f=c[d:]
print(e.upper())
print(f.lower())

#17.c
s=input("enter a string : ")
t=s.split()
for i in t:
 n=i[0].upper()+i[1:-1]+i[-1].upper()
 print(n,end=" ")

 #17.d
x=input("enter a string : ")
A=False
B=False
for i in x:
  if i.isalpha():
    A=True
  if i.isdigit():
    B=True
if A and B:
  print("yes")
else:
  print("no")


#17.e
a1=input("enter a string")
a2=a1.lower()
if 'a' in a2 and 'e' in a2 and 'o' in a2 and 'i' in a2 and 'u' in a2:
  print("the given string contain all vowels")
else:
  print("the given string does not contain all vowels")

#lab 18.a
a=input("enter the first string")
b=input("enter the second string")
count=0
for i in a :
  if i in b:
    count+=1
    b=b.replace(i,"",1)
print("total number of matches is :",count)


#18.b
c=input("enter the  string : ")
count=0
d={'a','e','i','o','u'}
for j in c:
  if j in d:
    count+=1
print("the numbers of vowels is :", count)


#18.c
e=input("enter the  string : ")
f=""
for ii in e:
  if ii not in f:
    f+=ii
print(f)

#18.d
m=input("enter the  string : ")
mcount=len(m)
mch=''
for i in m:
  count=m.count(i)
  if count<mcount:
    mcount=count
    mch=i
print("the character",mch,"occurs least of ",mcount,"times")

#18.e
mn=input("enter the  string : ")
mncount=1
mnch=''
for im in mn:
  countm=mn.count(im)
  if countm>mncount:
    mncount=countm
    mnch=im
print("the character",mnch,"occurs least of ",mncount,"times")

#18.f
x=input("enter the  string : ")
z=int(input("enter the k value"))
y=x.split()
for i in y:
  if len(i)>z:
    print(i)

#lab 19.a
x=input("enter the  string : ")
for i in x:
  if x.count(i)%2!=0:
    print(i)

#lab 19.b
y=input("enter the  string : ")
v=y.split()
z=input("enter the character")
for j in v:
  count=j.count(z)
  print(z, "appears" ,count ,"times in " ,j)


 #lab 19.c
a=input("enter a string")
count=0
for i in a:
  if i.isdigit():
    count=a.count(i)
    print(i, "appears ", count ,"times")

#lab 19.d
b=input("enter the  string : ")
for c in b:
  if c.isalnum()==False and c.isspace()==False and c!='_':
    print("the string contains special character")
    break
else:
  print("the string does not contain special character")


#lab 19.e
a=input("enter a string :")
b="hello how are you"
if a==b:
  print("matched")
else:
  print("not matched")


#lab 19.f
a=input("enter a string : ")
b=a.split()
print(b)
c="_".join(b)
print(c)

#lab 20.a
a=input("enter a string : ")
b=a[-1]+a[1:-1]+a[0]
print(b)

#lab 20.b
c=input("enter a string : ")
a=c.split()
d=int(input("enter 1st the element to swap"))
e=int(input("enter 2nd the element to swap"))
a[d],a[e]=a[e],a[d]
print(' '.join(a))

#20.c
a=input("enter a string : ")
b=a.split()
count=0
print(len(b))
for i in b:
  count+=1
print(count)

#20.d
a=[1,2,3,4]
b=int(input("enter the element"))
if b in a:
  print("yes")
else:
  print("no")

#20.e
a=[1,2,3,4]
print(a.clear())
a=[]
print(a)
print(a[:])

#lab 21
l=[1,2,3,4]
l.reverse()
print(l)

#21.b
a=[1,2,3,4]
s=0
for i in a:
  s+=i
print(s)

#21.c
l=[1,2,3,4,5,6,7,8,9,10]
m=1
for i in l:
  m*=i
print(m)

#21.d
b=input("enter string")
a=b.split()
min=a[0]
for i in a:
  if i<min:
    min=i
print(min)

#21.e
a=input("enter the string: ")
b=a.split()
max=a[0]
for i in b:
  if i>max:
    max=i
print(max)

#lab 22
a=input("enter the string: ")
b=a.split()
max=a[0]
for i in b:
  if i>max:
    max=i
b.remove(max)
max=a[0]
for i in b:
  if i>max:
    max=i
print(max)


#lab 22.b
a=[2,5,1,8,4,3]
n=int(input("enter the number of elements"))
c=[]
for i in range(n) :
  min=a[0]
  for j in a:
    if j>min:
     min=j
  c.append(min)
  a.remove(min)
print(c)

#lab 22.c,d
a=[1,2,3,4]
for i in a:
  if i%2!=0:
    print(i,end=" ")

#lab 23
a=[2,4,5,12,3,4,5]
b=int(input("enter range"))
for i in range (b):
  if a[i]%2==0:
    print(a[i])


#23.b,c
a=[1,2,-3,4,-1]
for i in a:
  if i<0:
    print(i)

#23.d,e
a=[1,2,-3,4,-1]
b=int(input("enter a range"))
for i in range(b):
  if a[i]<0:
    print(a[i])

#even numbers in a list
a=[1,2,3,4,5,6,7,8]
for i in a:
  if i%2==0:
    print(i)


#odd numbers in a list
b=[1,2,3,4,5,6,7,8]
for j in b:
  if j%2!=0:
    print(j,end=" ")

#even numbers in a range
a=[1,2,3,4,5,6,7,8]
num=int(input("enter the range: "))
for i in range(num):
  if a[i]%2==0:
    print(a[i])


#odd numbers in a range
b=[1,2,3,4,5,6,7,8]
num=int(input("enter the range: "))
for i in range(num):
  if b[i]%2!=0:
    print(b[i])