# -*- coding: utf-8 -*-
"""lab4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Fo9rJU-N_hxw__4EAaEqEYj7LpL_sdw
"""

#lab 24.a
a=[2,3,4,5,2,12,6,34,3,4]
b=list(map(int,input("enter elements to remove").split()))
for i in a:
  if i in b:
    a.remove(i)
print(a)


#24.b
a=[2,3,4,[],5,2,[],12,[],6,34,3,4]
for i in a[:] :
  if i==[]:
    a.remove(i)
print(a)


#24.c
a=[2,3,4,5,2,12,6,34,3,4]
b=a.copy()
print(a)
print(b)


#24.d
a=[2,3,4,5,2,12,6,34,3,4]
b=int(input("enter the element to count"))
count=0
for i in a:
  if i==b:
    count+=1
print(count)

#24.e
a=[(3),(2,3),(),(4)]
for i in a:
  if i ==():
    a.remove(i)
print(a)

#25.a
a=[2,3,4,5,2,12,6,34,3,4]
b=[]
for i in a:
  if a.count(i)>1 and i not in b:
    b.append(i)
print(b)


#25.b
a=[2,3,4,5,2,12,6,34,3,4]
b=[]
count=0
for i in a:
  count+=i
  b.append(count)
print(b)


#25.c
a=[12,44,52]
b=[]

for i in a:
  s=0
  for j in str(i):
    s=s+ int(j)
  b.append(s)
print(b)


#25.d
a=[1,2,4,6,3,5,87,35,7,9,2,5]
n=int(input("enter the no of chunks"))
b=[]
for i in range(0,len(a),n):
  b.append(a[i:i+n])
print(b)

a=0
b=1
print('0')
print('1')
c=a+b
while c<100:
  print(c)
  a=b
  b=c
  c=a+b

a=int(input("enter the first number"))
b=int(input("enter the second number"))
c=int(input("enter the second number"))
count=0
for d in range(a,b):
  i=d
  while i!=0:
    m=i%10
    if m==c:
       count+=1
    i=i//10
print(count)

for i in range (100,400):
 c=0
 b=i
 while b!=0:
  d=b%10
  c=(d*d*d)+c
  b=b//10
 if i==c:
  print(c)

count=0
n=400
i=1
while count<n:
 c=0
 b=i
 while b!=0:
  d=b%10
  c=(d*d*d)+c
  b=b//10
 if i==c:
  count+=1
  print(c)
 i+=1

a=int(input("enter the first number"))
b=int(input("enter the second number"))
for i in range(a,b):
  if i>1:
    for j in range(2,i):
      if i%j==0:
        print(i)
        break

r=0
a=121
b=a
while b!=0:
  d=b%10
  r=r*10+d
  b=b//10
if a==r:
  print("yes")

a=input("enter string")
for i in a:
  if a.count(i)%2!=0:
    print(a)
  break

a=input("enter string")
b=input("enter character")
c=0
for i in a:
  c=a.count(b)
  print(b,"appears",c ,"times in string")
  break

a=input("enter string")
count=0
for i in a:
  if i.isdigit():
    count=a.count(i)
    print(i,"appears",count,"times")

a=input("enter string")
for i in a:
  if i.isalnum()==False and i.isspace()==False and i!='_':
    print("yes")
    break

a=input("enter string")
b=a.split()
c="_".join(b)
print(b,c)

a=[1,3,4,3,5,9,7]
b=int(input("enter n"))
c=[]
for i in range(b):
  min=a[0]
  for j in a:
    if j<min:
      min=j
  c.append(min)
  a.remove(min)
  max=a[0]
print(c)

a=['apple','banana','mango']
b=[3,2,1]
for i in range(len(a)):
  for j in range(i+1,len(a)):
    b[i],b[j]=b[j],b[i]
    a[i],a[j]=a[j],a[i]
print(a)

a=input("enter a string")
l=len(a)
m=len(a)//2

if l%2==0:
  b=a[:m]
  c=a[m:]

else:
  b=a[:m]
  c=a[m+1:]

if b==c:
  print("symmetrical")
else:
  print("not symmetrical")

add=lambda x,y:x+y
print("the sum is ",add(10,20))

